// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package repo

import (
	"trackion/internal/db/models"

	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
	"gorm.io/datatypes"
)

var Config = struct {
	ID        field.Field[uuid.UUID]
	ProjectID field.Field[uuid.UUID]
	Key       field.String
	Value     field.Field[datatypes.JSON]
	CreatedAt field.Time
	UpdatedAt field.Time
	Project   field.Struct[models.Project]
}{
	ID:        field.Field[uuid.UUID]{}.WithColumn("id"),
	ProjectID: field.Field[uuid.UUID]{}.WithColumn("project_id"),
	Key:       field.String{}.WithColumn("key"),
	Value:     field.Field[datatypes.JSON]{}.WithColumn("value"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	Project:   field.Struct[models.Project]{}.WithName("Project"),
}
