// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package repo

import (
	"trackion/internal/db/models"

	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
	"gorm.io/datatypes"
)

var Event = struct {
	ID          field.Number[int64]
	ProjectID   field.Field[uuid.UUID]
	EventName   field.String
	EventType   field.String
	UserID      field.String
	SessionID   field.String
	Platform    field.String
	Device      field.String
	OSVersion   field.String
	AppVersion  field.String
	Browser     field.String
	PagePath    field.String
	PageTitle   field.String
	Referrer    field.String
	UTMSource   field.String
	UTMMedium   field.String
	UTMCampaign field.String
	Properties  field.Field[datatypes.JSON]
	CreatedAt   field.Time
	Project     field.Struct[models.Project]
}{
	ID:          field.Number[int64]{}.WithColumn("id"),
	ProjectID:   field.Field[uuid.UUID]{}.WithColumn("project_id"),
	EventName:   field.String{}.WithColumn("event_name"),
	EventType:   field.String{}.WithColumn("event_type"),
	UserID:      field.String{}.WithColumn("user_id"),
	SessionID:   field.String{}.WithColumn("session_id"),
	Platform:    field.String{}.WithColumn("platform"),
	Device:      field.String{}.WithColumn("device"),
	OSVersion:   field.String{}.WithColumn("os_version"),
	AppVersion:  field.String{}.WithColumn("app_version"),
	Browser:     field.String{}.WithColumn("browser"),
	PagePath:    field.String{}.WithColumn("page_path"),
	PageTitle:   field.String{}.WithColumn("page_title"),
	Referrer:    field.String{}.WithColumn("referrer"),
	UTMSource:   field.String{}.WithColumn("utm_source"),
	UTMMedium:   field.String{}.WithColumn("utm_medium"),
	UTMCampaign: field.String{}.WithColumn("utm_campaign"),
	Properties:  field.Field[datatypes.JSON]{}.WithColumn("properties"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	Project:     field.Struct[models.Project]{}.WithName("Project"),
}
