// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package repo

import (
	"trackion/internal/db/models"

	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
)

var Flag = struct {
	ID                field.Field[uuid.UUID]
	ProjectID         field.Field[uuid.UUID]
	Key               field.String
	Enabled           field.Bool
	RolloutPercentage field.Number[int]
	CreatedAt         field.Time
	UpdatedAt         field.Time
	Project           field.Struct[models.Project]
}{
	ID:                field.Field[uuid.UUID]{}.WithColumn("id"),
	ProjectID:         field.Field[uuid.UUID]{}.WithColumn("project_id"),
	Key:               field.String{}.WithColumn("key"),
	Enabled:           field.Bool{}.WithColumn("enabled"),
	RolloutPercentage: field.Number[int]{}.WithColumn("rollout_percentage"),
	CreatedAt:         field.Time{}.WithColumn("created_at"),
	UpdatedAt:         field.Time{}.WithColumn("updated_at"),
	Project:           field.Struct[models.Project]{}.WithName("Project"),
}
