// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package repo

import (
	"trackion/internal/db/models"

	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

var Project = struct {
	ID                 field.Field[uuid.UUID]
	Name               field.String
	UserID             field.Field[uuid.UUID]
	Status             field.String
	ApiKey             field.String
	Properties         field.Field[datatypes.JSON]
	Domains            field.Field[datatypes.JSON]
	EventRetentionDays field.Number[int]
	CreatedAt          field.Time
	UpdatedAt          field.Time
	DeletedAt          field.Field[gorm.DeletedAt]
	Events             field.Slice[models.Event]
	Flags              field.Slice[models.Flag]
	Configs            field.Slice[models.Config]
	User               field.Struct[models.User]
}{
	ID:                 field.Field[uuid.UUID]{}.WithColumn("id"),
	Name:               field.String{}.WithColumn("name"),
	UserID:             field.Field[uuid.UUID]{}.WithColumn("user_id"),
	Status:             field.String{}.WithColumn("status"),
	ApiKey:             field.String{}.WithColumn("api_key"),
	Properties:         field.Field[datatypes.JSON]{}.WithColumn("properties"),
	Domains:            field.Field[datatypes.JSON]{}.WithColumn("domains"),
	EventRetentionDays: field.Number[int]{}.WithColumn("event_retention_days"),
	CreatedAt:          field.Time{}.WithColumn("created_at"),
	UpdatedAt:          field.Time{}.WithColumn("updated_at"),
	DeletedAt:          field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Events:             field.Slice[models.Event]{}.WithName("Events"),
	Flags:              field.Slice[models.Flag]{}.WithName("Flags"),
	Configs:            field.Slice[models.Config]{}.WithName("Configs"),
	User:               field.Struct[models.User]{}.WithName("User"),
}
