// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package repo

import (
	"context"
	"strings"

	"gorm.io/cli/gorm/typed"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func Query[T any](db *gorm.DB, opts ...clause.Expression) _QueryInterface[T] {
	return _QueryImpl[T]{
		Interface: typed.G[T](db, opts...),
	}
}

type _QueryInterface[T any] interface {
	typed.Interface[T]
	GetByID(ctx context.Context, id string) (T, error)
	GetUserByEmail(ctx context.Context, email string) (T, error)
	GetUserByProvider(ctx context.Context, providerId string) (T, error)
	UpdateUserFromProvider(ctx context.Context, providerId string, email string, name string, avatarURL string) error
}

type _QueryImpl[T any] struct {
	typed.Interface[T]
}

func (e _QueryImpl[T]) GetByID(ctx context.Context, id string) (T, error) {
	var sb strings.Builder
	_params := make([]any, 0, 2)

	sb.WriteString("SELECT * FROM ? WHERE id=?")
	_params = append(_params, clause.Table{Name: clause.CurrentTable}, id)

	var result T
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _QueryImpl[T]) GetUserByEmail(ctx context.Context, email string) (T, error) {
	var sb strings.Builder
	_params := make([]any, 0, 1)

	sb.WriteString("SELECT * FROM user WHERE email=?")
	_params = append(_params, email)

	var result T
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _QueryImpl[T]) GetUserByProvider(ctx context.Context, providerId string) (T, error) {
	var sb strings.Builder
	_params := make([]any, 0, 2)

	sb.WriteString("SELECT * FROM user WHERE github_id=? OR google_id=?")
	_params = append(_params, providerId, providerId)

	var result T
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _QueryImpl[T]) UpdateUserFromProvider(ctx context.Context, providerId string, email string, name string, avatarURL string) error {
	var sb strings.Builder
	_params := make([]any, 0, 5)

	sb.WriteString("UPDATE user SET email=?, name=?, avatar_url=? WHERE github_id=? OR google_id=?")
	_params = append(_params, email, name, avatarURL, providerId, providerId)

	return e.Exec(ctx, sb.String(), _params...)
}
