// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package repo

import (
	"trackion/internal/db/models"

	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
)

var ReplayChunk = struct {
	ID        field.Number[int64]
	SessionID field.String
	ProjectID field.Field[uuid.UUID]
	Data      field.Bytes
	CreatedAt field.Time
	Project   field.Struct[models.Project]
}{
	ID:        field.Number[int64]{}.WithColumn("id"),
	SessionID: field.String{}.WithColumn("session_id"),
	ProjectID: field.Field[uuid.UUID]{}.WithColumn("project_id"),
	Data:      field.Bytes{}.WithColumn("data"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	Project:   field.Struct[models.Project]{}.WithName("Project"),
}
