// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package repo

import (
	"trackion/internal/db/models"

	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
)

var ReplaySession = struct {
	SessionID  field.String
	ProjectID  field.Field[uuid.UUID]
	StartedAt  field.Time
	LastSeenAt field.Time
	Project    field.Struct[models.Project]
}{
	SessionID:  field.String{}.WithColumn("session_id"),
	ProjectID:  field.Field[uuid.UUID]{}.WithColumn("project_id"),
	StartedAt:  field.Time{}.WithColumn("started_at"),
	LastSeenAt: field.Time{}.WithColumn("last_seen_at"),
	Project:    field.Struct[models.Project]{}.WithName("Project"),
}
