// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package repo

import (
	"trackion/internal/db/models"

	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
)

var Session = struct {
	ID        field.Field[uuid.UUID]
	UserID    field.Field[uuid.UUID]
	Token     field.String
	CreatedAt field.Time
	ExpiresAt field.Time
	User      field.Struct[models.User]
}{
	ID:        field.Field[uuid.UUID]{}.WithColumn("id"),
	UserID:    field.Field[uuid.UUID]{}.WithColumn("user_id"),
	Token:     field.String{}.WithColumn("token"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	ExpiresAt: field.Time{}.WithColumn("expires_at"),
	User:      field.Struct[models.User]{}.WithName("User"),
}
