// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package repo

import (
	"trackion/internal/db/models"

	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
)

var Subscription = struct {
	ID                  field.Field[uuid.UUID]
	UserID              field.Field[uuid.UUID]
	Plan                field.String
	Status              field.String
	MonthlyEventLimit   field.Number[int]
	CurrentPeriodEnd    field.Time
	EventsUsedThisMonth field.Number[int]
	ProjectsUsed        field.Number[int]
	LastUsageReset      field.Time
	MaxProjects         field.Number[int]
	MaxConfigKeys       field.Number[int]
	ErrorRetentionDays  field.Number[int]
	SupportsRollout     field.Bool
	CreatedAt           field.Time
	UpdatedAt           field.Time
	User                field.Struct[models.User]
}{
	ID:                  field.Field[uuid.UUID]{}.WithColumn("id"),
	UserID:              field.Field[uuid.UUID]{}.WithColumn("user_id"),
	Plan:                field.String{}.WithColumn("plan"),
	Status:              field.String{}.WithColumn("status"),
	MonthlyEventLimit:   field.Number[int]{}.WithColumn("monthly_event_limit"),
	CurrentPeriodEnd:    field.Time{}.WithColumn("current_period_end"),
	EventsUsedThisMonth: field.Number[int]{}.WithColumn("events_used_this_month"),
	ProjectsUsed:        field.Number[int]{}.WithColumn("projects_used"),
	LastUsageReset:      field.Time{}.WithColumn("last_usage_reset"),
	MaxProjects:         field.Number[int]{}.WithColumn("max_projects"),
	MaxConfigKeys:       field.Number[int]{}.WithColumn("max_config_keys"),
	ErrorRetentionDays:  field.Number[int]{}.WithColumn("error_retention_days"),
	SupportsRollout:     field.Bool{}.WithColumn("supports_rollout"),
	CreatedAt:           field.Time{}.WithColumn("created_at"),
	UpdatedAt:           field.Time{}.WithColumn("updated_at"),
	User:                field.Struct[models.User]{}.WithName("User"),
}
