// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package repo

import (
	"trackion/internal/db/models"

	"github.com/google/uuid"
	"gorm.io/cli/gorm/field"
)

var User = struct {
	ID           field.Field[uuid.UUID]
	AvatarUrl    field.String
	Email        field.String
	Name         field.String
	GithubID     field.String
	GoogleID     field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
	Subscription field.Struct[models.Subscription]
	Sessions     field.Slice[models.Session]
	Projects     field.Slice[models.Project]
}{
	ID:           field.Field[uuid.UUID]{}.WithColumn("id"),
	AvatarUrl:    field.String{}.WithColumn("avatar_url"),
	Email:        field.String{}.WithColumn("email"),
	Name:         field.String{}.WithColumn("name"),
	GithubID:     field.String{}.WithColumn("github_id"),
	GoogleID:     field.String{}.WithColumn("google_id"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
	UpdatedAt:    field.Time{}.WithColumn("updated_at"),
	Subscription: field.Struct[models.Subscription]{}.WithName("Subscription"),
	Sessions:     field.Slice[models.Session]{}.WithName("Sessions"),
	Projects:     field.Slice[models.Project]{}.WithName("Projects"),
}
