// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package repository

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertEventsBatch = `-- name: InsertEventsBatch :batchexec
INSERT INTO events (
    project_id,
    event_name,
    session_id,
    page_path,
    page_title,
    referrer,
    utm_source,
    utm_medium,
    utm_campaign,
    properties
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertEventsBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertEventsBatchParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	EventName   string    `json:"event_name"`
	SessionID   *string   `json:"session_id"`
	PagePath    *string   `json:"page_path"`
	PageTitle   *string   `json:"page_title"`
	Referrer    *string   `json:"referrer"`
	UtmSource   *string   `json:"utm_source"`
	UtmMedium   *string   `json:"utm_medium"`
	UtmCampaign *string   `json:"utm_campaign"`
	Properties  []byte    `json:"properties"`
}

func (q *Queries) InsertEventsBatch(ctx context.Context, arg []InsertEventsBatchParams) *InsertEventsBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ProjectID,
			a.EventName,
			a.SessionID,
			a.PagePath,
			a.PageTitle,
			a.Referrer,
			a.UtmSource,
			a.UtmMedium,
			a.UtmCampaign,
			a.Properties,
		}
		batch.Queue(insertEventsBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertEventsBatchBatchResults{br, len(arg), false}
}

func (b *InsertEventsBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertEventsBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
