// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (project_id, event_name, session_id, properties)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertEventParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	EventName  string      `json:"event_name"`
	SessionID  pgtype.Text `json:"session_id"`
	Properties []byte      `json:"properties"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ProjectID,
		arg.EventName,
		arg.SessionID,
		arg.Properties,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertEventsBatch = `-- name: InsertEventsBatch :exec
INSERT INTO events ( project_id, event_name, session_id, properties)
SELECT
    unnest($1::uuid[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::jsonb[])
`

type InsertEventsBatchParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []string    `json:"column_2"`
	Column3 []string    `json:"column_3"`
	Column4 [][]byte    `json:"column_4"`
}

func (q *Queries) InsertEventsBatch(ctx context.Context, arg InsertEventsBatchParams) error {
	_, err := q.db.Exec(ctx, insertEventsBatch,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}
