// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID         int64       `json:"id"`
	ProjectID  uuid.UUID   `json:"project_id"`
	EventName  string      `json:"event_name"`
	SessionID  pgtype.Text `json:"session_id"`
	Properties []byte      `json:"properties"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Project struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	ApiKey    string    `json:"api_key"`
	CreatedAt time.Time `json:"created_at"`
}
