// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    id,
    user_id,
    plan,
    monthly_event_limit,
    status,
    current_period_end
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, plan, monthly_event_limit, status, current_period_end, created_at
`

type CreateSubscriptionParams struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Plan              string             `json:"plan"`
	MonthlyEventLimit int32              `json:"monthly_event_limit"`
	Status            string             `json:"status"`
	CurrentPeriodEnd  pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.UserID,
		arg.Plan,
		arg.MonthlyEventLimit,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.MonthlyEventLimit,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSubscriptionByUser = `-- name: GetActiveSubscriptionByUser :one
SELECT id, user_id, plan, monthly_event_limit, status, current_period_end, created_at
FROM subscriptions
WHERE user_id = $1
  AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionByUser(ctx context.Context, userID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByUser, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.MonthlyEventLimit,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSubscriptionLimitByProject = `-- name: GetActiveSubscriptionLimitByProject :one
SELECT s.monthly_event_limit
FROM projects p
JOIN subscriptions s ON s.user_id = p.owner_id
WHERE p.id = $1
  AND s.status = 'active'
ORDER BY s.created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionLimitByProject(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionLimitByProject, id)
	var monthly_event_limit int32
	err := row.Scan(&monthly_event_limit)
	return monthly_event_limit, err
}

const getMonthlyUsageByProject = `-- name: GetMonthlyUsageByProject :one
SELECT COUNT(e.id)::bigint AS usage_count
FROM events e
JOIN projects p ON p.id = e.project_id
WHERE p.id = $1
  AND e.created_at >= date_trunc('month', now())
`

func (q *Queries) GetMonthlyUsageByProject(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMonthlyUsageByProject, id)
	var usage_count int64
	err := row.Scan(&usage_count)
	return usage_count, err
}

const getMonthlyUsageByUser = `-- name: GetMonthlyUsageByUser :one
SELECT COUNT(e.id)::bigint AS usage_count
FROM events e
JOIN projects p ON p.id = e.project_id
WHERE p.owner_id = $1
  AND e.created_at >= date_trunc('month', now())
`

func (q *Queries) GetMonthlyUsageByUser(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMonthlyUsageByUser, ownerID)
	var usage_count int64
	err := row.Scan(&usage_count)
	return usage_count, err
}

const renewFreeSubscriptionsForNewMonth = `-- name: RenewFreeSubscriptionsForNewMonth :execrows
UPDATE subscriptions
SET current_period_end = date_trunc('month', now()) + INTERVAL '1 month'
WHERE status = 'active'
  AND plan = 'free'
  AND (current_period_end IS NULL OR current_period_end <= now())
`

func (q *Queries) RenewFreeSubscriptionsForNewMonth(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, renewFreeSubscriptionsForNewMonth)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewUserFreeSubscriptionIfNeeded = `-- name: RenewUserFreeSubscriptionIfNeeded :exec
UPDATE subscriptions
SET current_period_end = date_trunc('month', now()) + INTERVAL '1 month'
WHERE user_id = $1
  AND status = 'active'
  AND plan = 'free'
  AND (current_period_end IS NULL OR current_period_end <= now())
`

func (q *Queries) RenewUserFreeSubscriptionIfNeeded(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, renewUserFreeSubscriptionIfNeeded, userID)
	return err
}
