services:
  trackion:
    image: ghcr.io/p8labs/trackion:latest
    container_name: trackion
    restart: unless-stopped
    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "1001:1001"
